//$Archive: /VP/END-USER/DLLS/mvCommonMechanisms/inc/mvIPCAcknowledgeEventPoolManager.h $
/*

(c) Copyright Matrox Electronic Systems Ltd., 2003. All rights reserved. 

This code and information is provided "as is" without warranty of any kind, 
either expressed or implied, including but not limited to the implied 
warranties of merchantability and/or fitness for a particular purpose.

Disclaimer: Matrox Electronic Systems Ltd. reserves the right to make 
changes in specifications and code at any time and without notice. 
No responsibility is assumed by Matrox Electronic Systems Ltd. for 
its use; nor for any infringements of patents or other rights of 
third parties resulting from its use. No license is granted under 
any patents or patent rights of Matrox Electronic Systems Ltd.

*/

/* Generated by Together */

#ifndef MVIPCACKNOWLEDGEEVENTPOOLMANAGER_H_
#define MVIPCACKNOWLEDGEEVENTPOOLMANAGER_H_

#include "mvUtility.h"
#include "mvTypes.h" //For uint64_t
#ifndef LINUX_PLATFORM
#pragma warning( disable : 4702 ) //Disable "unreachable code" warning
#endif	
#include <list>
#include <map>
#ifndef LINUX_PLATFORM
#pragma warning( default : 4702 )
#endif	
#include "mvIPCAcknowledgeEventPoolElement.h"

const int g_ciAcknwoledgeEventPoolSize = 10;

class CMvIPCAcknowledgeEventPoolManager
{
public:    
	//==========================================================================;
	// Public operations
	//==========================================================================;
	CMvIPCAcknowledgeEventPoolManager();
	virtual ~CMvIPCAcknowledgeEventPoolManager();

	CMvIPCAcknowledgeEventPoolElement * GetFreeAcknowledgeEvent();
	void ReturnFreeAckowledgeEvent(CMvIPCAcknowledgeEventPoolElement * in_pAckowledgeEvent);
	CMvEvent * GetAcknowledgeEventFromID(uint64_t in_ui64AcknowledgeEventID);

protected:
	CMvMutex * m_poMutex;

	uint64_t m_ui64UniqueID;
	std::list<CMvIPCAcknowledgeEventPoolElement*> m_loFreeAcknowledgeEvents;
	std::map<uint64_t, CMvIPCAcknowledgeEventPoolElement*> m_mapAcknowledgeEventPoolElement;
};
#endif //MVIPCACKNOWLEDGEEVENTPOOLMANAGER_H_

